Ticket 3
dzhiblavi/dbms-conspect pull request #13
Opened 2022-01-06 09:44 UTC by AndreyBocharnikov

2022-01-06 10:39 UTC, dzhiblavi requested changes
Все еще не работает формат хук :(

2022-01-06 10:39 UTC, dzhiblavi commented on src/theory/ticket-3.tex
> +таких РСУБД есть девелоперские лицензии, которые позволяют использовать их в ограниченной среде (ограничение на кол-во ядер и размер памяти).
девелоперские?? можно русское слово

2022-01-06 10:39 UTC, dzhiblavi commented on src/theory/ticket-3.tex
> +		      \item непосредственная поддержка связей - СУБД достаточно стабильна, чтобы использовать в реальных проектах
Нужно тире, а не дефис, такое много где

2022-01-06 10:39 UTC, dzhiblavi commented on src/theory/ticket-3.tex
> +		      \item компактна, поэтому много используется на мобильных устройствах
Формат списков все еще совсем не тот (см. другие билеты)

2022-01-06 11:29 UTC, AndreyBocharnikov commented on src/theory/ticket-3.tex
> +		      \item компактна, поэтому много используется на мобильных устройствах
его ручками нужно нужный писать или хук должен исправлять? это после хука такое форматирование

2022-01-07 11:04 UTC, Garuda-1 requested changes
Пожалуйста, называй ветки в соответствии с соглашением.
`ticket/t-<номер>-<фамилия>`

2022-01-07 11:14 UTC, dzhiblavi approved these changes

2022-01-07 11:15 UTC, dzhiblavi approved these changes

2022-01-07 11:15 UTC, merged