ticket-16 (Соединения)
dzhiblavi/dbms-conspect pull request #16
Opened 2022-01-06 12:20 UTC by dzhiblavi

2022-01-07 12:41 UTC, Garuda-1 requested changes

2022-01-07 12:41 UTC, Garuda-1 commented on src/theory/ticket-16.tex
> +\end{definition}
Я бы уточнил, что атрибуты, по равным значениям которых производится объединение, должны иметь одинаковые имена.

2022-01-07 12:41 UTC, Garuda-1 commented on src/theory/ticket-16.tex
> +\end{definition}
Можно случайно посчитать, что сохраняет **только** те кортежи, для которых нет соответствующих во втором отношении. Лучше явно добавить, что эти кортежи добавляются дополнительно к тем, которые дает естественное соединение.

2022-01-07 18:48 UTC, dzhiblavi commented on src/theory/ticket-16.tex
> +\end{definition}
Поправил

2022-01-07 18:48 UTC, dzhiblavi commented on src/theory/ticket-16.tex
> +\end{definition}
Поправил

2022-01-08 09:06 UTC, Garuda-1 requested changes

2022-01-08 09:06 UTC, Garuda-1 commented on src/theory/ticket-16.tex
> +	соответствующего берется пустой кортеж. Заголовком все так же является объединение заголовков.
объединение -> объединением

2022-01-08 09:06 UTC, Garuda-1 commented on src/theory/ticket-16.tex
> +\end{definition}
Мне самому при чтении неясно, что означает "сохранить только из левого (правого) отношения" в этом определении. Можешь переформулировать, пожалуйста?

2022-01-08 10:06 UTC, dzhiblavi commented on src/theory/ticket-16.tex
> +	соответствующего берется пустой кортеж. Заголовком все так же является объединение заголовков.
Не очень понял(

2022-01-08 10:07 UTC, dzhiblavi commented on src/theory/ticket-16.tex
> +\end{definition}
Вроде как это достаточно стандартный способ делать 2 определения в одном для симметричных понятий. Но ладно, перепишу как-нибудь по-другому

2022-01-08 10:19 UTC, Garuda-1 commented on src/theory/ticket-16.tex
> +	соответствующего берется пустой кортеж. Заголовком все так же является объединение заголовков.
Смотрел в старую версию, отбой

2022-01-08 10:20 UTC, Garuda-1 commented on src/theory/ticket-16.tex
> +\end{definition}
Я не про это, а про то, что сам термин "сохранить" тут неясен.

2022-01-08 11:27 UTC, dzhiblavi commented on src/theory/ticket-16.tex
> +\end{definition}
Поправил

2022-01-08 12:19 UTC, Garuda-1 approved these changes
При желании, поправь определение левого и правого соединений, пожалуйста.

2022-01-09 13:59 UTC, dzhiblavi commented on src/theory/ticket-16.tex
> +\end{definition}
Поправил и то что имелось в виду

2022-01-09 14:01 UTC, merged