Init theory ticket 31
dzhiblavi/dbms-conspect pull request #4
Opened 2022-01-04 22:44 UTC by Garuda-1

2022-01-05 21:06 UTC, dzhiblavi requested changes

2022-01-05 21:06 UTC, dzhiblavi commented on src/theory/ticket-31.tex
> +Про транзакции и восстановление БД после сбоев, можно прочитать в предыдущем билете.
Может "В разделе \ref{...}" будет лучше?

2022-01-06 09:54 UTC, Garuda-1 commented on src/theory/ticket-31.tex
> +Про транзакции и восстановление БД после сбоев, можно прочитать в предыдущем билете.
Согласен, исправил.

2022-01-06 10:40 UTC, dzhiblavi approved these changes

2022-01-06 10:40 UTC, merged