ticket-32 (Транзакции. Параллельное исполнение. Блокировки.)
dzhiblavi/dbms-conspect pull request #6
Opened 2022-01-05 12:41 UTC by Garuda-1

2022-01-05 21:07 UTC, dzhiblavi requested changes

2022-01-05 21:07 UTC, dzhiblavi commented on src/theory/ticket-32.tex
> +Напомним, что свойство \textit{изоляции (isolation)} транзакции подразумевает, что она должна исполняться
Можно ссылку на определение сделать

2022-01-06 09:58 UTC, Garuda-1 commented on src/theory/ticket-32.tex
> +Напомним, что свойство \textit{изоляции (isolation)} транзакции подразумевает, что она должна исполняться
Тогда сначала придется вмерджить #4

2022-01-06 10:40 UTC, dzhiblavi commented on src/theory/ticket-32.tex
> +Напомним, что свойство \textit{изоляции (isolation)} транзакции подразумевает, что она должна исполняться
Вмержил

2022-01-06 11:18 UTC, Garuda-1 commented on src/theory/ticket-32.tex
> +Напомним, что свойство \textit{изоляции (isolation)} транзакции подразумевает, что она должна исполняться
Починил, но Files changed показывает что-то страшное

2022-01-06 12:23 UTC, dzhiblavi requested changes
Кажется не нормально, что в этом ПР есть куча тикетов вместо одного

2022-01-06 12:26 UTC, dzhiblavi approved these changes

2022-01-06 12:26 UTC, merged