first ticket done
dzhiblavi/dbms-conspect pull request #9
Opened 2022-01-05 19:02 UTC by AndreyBocharnikov

2022-01-05 21:05 UTC, dzhiblavi requested changes
В целом файл явно не отформатировался (должен был сработать хук если ты сделал sync перед коммитом). Поправишь остальное -- отформатирую сам.

2022-01-05 21:05 UTC, dzhiblavi commented on src/theory/ticket-1.tex
> +    \item  заголовок - название столбцов
Посмотри как форматируются списки в других билетах

2022-01-05 21:05 UTC, dzhiblavi commented on src/theory/ticket-1.tex
> +    \item мн-во вещей делается в коде
Можно без сокращений пожалусто...

2022-01-07 11:02 UTC, dzhiblavi approved these changes

2022-01-07 11:02 UTC, merged

2022-01-07 11:03 UTC, Garuda-1 requested changes
Пожалуйста, называй ветки в соответствии с соглашением.
`ticket/t-<номер>-<фамилия>`